DROP SCHEMA `fooo` IF EXISTS;

CREATE SCHEMA `fooo`;

SET SCHEMA `fooo`;

CREATE TABLE IF NOT EXISTS `fooo`.`POST` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONTENT` VARCHAR(45) NULL,
  `CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `fooo`.`COMMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fooo`.`COMMENT` (
  `ID` INT NOT NULL,
  `POST_ID` INT NULL,
  `CONTENT` VARCHAR(45) NULL,
  `CTIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `MTIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`));

